### ISSUE TITLE
Will Turi get GPU support for AMD's ROCm software platform?

### ISSUE THREAD

**Issue by helloniklas** [apple/turicreate#107]
I see AMD Vega GPU that is in the new iMac Pro is being marketed as excellent for machine learning with their new ROCm software platform that apparently has tensor flow support coming.

Will Turi Create be able to take advantage of this GPU with an iMac Pro?

**Comment by alkravchenko** [comment]
I think that Metal (MPS) support would be event better, because of mac GPU models list and Core ML GPU’s support. Metal supports AMD, NVidia and even Intel GPU’s. In ideal case we don’t want to think about hardware. And It would be great if Turi Create will chose optimal hardware backend themself as CoreML do in case of CPU/GPU choise.

**Comment by alkravchenko** [comment]
I wrote new issue with that notes - https://github.com/apple/turicreate/issues/115

**Comment by srikris** [comment]
We are looking into this. We will use the issue in #115 to track the issue.
