### ISSUE TITLE
Figure missing from regression user guide

### ISSUE THREAD

**Issue by afranklin** [apple/turicreate#1092]
**Observed Behavior:**
User guide page: https://apple.github.io/turicreate/docs/userguide/supervised-learning/regression.html

“The following figure depicts a sample supervised learning model where the training data (depicted in blue) is used to learn a function (depicted in pink) which can then be used in the future to make predictions.”

No figure on page

**Expected Behavior:**
Figure to be present on page.
Figure properly appears on old user guide version: https://turi.com/learn/userguide/supervised-learning/regression.html

**Comment by syoutsey** [comment]
I believe the root cause of this is that we're not loading the `D3` library which prevents us from drawing the charts. After research into the way Gitbook builds projects from the Markdown source, I can't find a simple way to include something like `<script src='d3.js'>...`. @znation or @hoytak do you know if I can get access to the git repo at the old [Turi site](https://turi.com/learn/userguide/supervised-learning/linear-regression.html) to check how we're building it there?
