### ISSUE TITLE
Run styleTransfer on Windows 10 (via WSL) with GPU(nv)??

### ISSUE THREAD

**Issue by tankfly2014** [apple/turicreate#1108]
my pc (Windows 10 (via WSL) ) version:Ubuntu >= 16.04
GPU RAM=6GB.

Support run styleTransfer with Gpu(nv) with Ubuntu (win10 (via WSL) )?
AND
Support run styleTransfer with Gpu(nv) with only Ubuntu(pc) ?

I find here:
https://github.com/apple/turicreate/issues/897
https://github.com/apple/turicreate/issues/896

**Comment by znation** [comment]
Support for Turi Create using the GPU in WSL will depend on support for CUDA in WSL: https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/16108045-opencl-cuda-gpu-support -- this is currently an open feature request for WSL. In the meantime this is not expected to work; workarounds would be to use CPU for training, or to use Ubuntu on bare metal instead of through WSL.

**Comment by tankfly2014** [comment]
ok.thank you very much.
