### ISSUE TITLE
Inconsistent groupby aggregation between SUM and MEAN

### ISSUE THREAD

**Issue by davidswaven** [apple/turicreate#116]
Summing over None values in an SArray returns 0.0.
I think we would expect aggregation on SUM to return None instead of 0.

Doing the same with MEAN returns None, as expected.
```
import turicreate as tc
import turicreate.aggregate as agg
sf = tc.SFrame({'c1': ['a'], 'c2': [None]})
```

`sf.groupby('c1', agg.SUM('c2'))`
returns 
Data:
+----+-----------+
_| c1 | Sum of c2 |_
+----+-----------+
| a  |    0.0    |
+----+-----------+
[1 rows x 2 columns]

while `sf.groupby('c1', agg.MEAN('c2'))`
returns 
_Data:_
+----+-----------+
| c1 | Avg of c2 |
+----+-----------+
| a  |    None   |
+----+-----------+
_[1 rows x 2 columns]_

**Comment by srikris** [comment]
At first, I thought this was a bug but now on second thought, I think this is correct behavior. There are 2 concepts:

1. All group-by operators in turicreate follow the skip None policy i.e they will omit all missing values from the aggregation.  As an example, `sum([None, 5, 10]) = 15` if you assume that the None is skipped. 
2. Additionally, in python/pandas/numpy etc, `sum([]) = 0` which is exactly what turicreate does as well. 

Hence, using the skip None policy and the sum of nothing is 0 policy, we get an answer of zero when you are trying to do `sum([None]) = sum([]) = 0` for the group `a`.

With the same principle in mind, we cannot get 0.0 for the mean because the mean is undefined if there are no points. Hence, using the skip None policy, we have `mean([None]) = sum([]) = None (undefined)` and hence you get None.

We can make the case that None values are skipped more clear in the groupby documentation. I'll file a separate issue for that.
