### ISSUE TITLE
Recommender with ProductID and UserID

### ISSUE THREAD

**Issue by dogahe** [apple/turicreate#1182]
I have trained a recommender system with only **ProductID** and **UserID** and I wish to be able to pass only **UserID** within my iOS App to get ProductID recommendations. But when I am trying to use this model in the iOS app, the model expects `interactions` which is defined as `The user's interactions, represented as a dictionary, where the keys are the item IDs, and the values are sentinel values.` So I am not clear how I can use this model in the iOS app by just passing a UserID, even though in the TuriCreate I can simply call `model.recommend(users=["myuser1id"])` to get ProductID recommendations for myuser1id.

**Comment by znation** [comment]
Hi @dogahe, the reason the model in CoreML only supports interactions and not users for querying is that we typically don't want each user to get access to the interaction history of all users. If the model were to allow for querying by user ID, since it's the same model for all users, any user could in theory query for any other user's recommendations without knowing their interaction history (or even open up the model file and examine other users' interaction history directly, if they have access to it). As the model developer in Turi Create, this doesn't expose any information it shouldn't (since you are starting with the data comprised of interaction history for all users anyway), but for privacy reasons we don't expect that such a database should be given to all the users of your app.

Presumably the use case for an on-device recommender model is to get recommendations for the current user (not necessarily any other user). And our assumption is that for the current user, it should be possible to programmatically retrieve their historical interactions. Could that assumption allow you to query for the recommendations for the current user? (Note: this also means the current user didn't necessarily need to be in the training data, whereas if you query by user ID they would need to be.)

To give an example, suppose the user ID is `1234`, and their interactions within the app are rating items `x`, `y`, and `z`, each with rating 5 (note: use `-1` as a placeholder if the model was trained without explicit ratings). So to get the same result as calling `recommend(users=[1234])` in Python, you'd call something like `[model predictionWithInteractions:@[@"x": 5, @"y": 2, @"z": 3] k:5]` in Objective C using the CoreML model. This is the equivalent of the [`recommend_from_interactions`](https://apple.github.io/turicreate/docs/api/generated/turicreate.recommender.item_similarity_recommender.ItemSimilarityRecommender.recommend_from_interactions.html#turicreate.recommender.item_similarity_recommender.ItemSimilarityRecommender.recommend_from_interactions) in Python.

Please let us know if this works for your use case, or if not, why not. For now I'll leave this issue open as a doc bug, since we should update the [user guide chapter](https://apple.github.io/turicreate/docs/userguide/recommender/coreml-deployment.html) to make it clear how to consume the Core ML model.

**Comment by dogahe** [comment]
Hi Zach @znation, I appreciate your explanation. I do see the value of having the capability to send the user interactions to get recommendations for that user. However, I do not understand the privacy concerns you have raised. Of course I, as the developer of the model, have access to all users data. And if I use this model in my iOS app and the only call within that iOS app is to get product recommendations for the current identified and authorized user, I am not sure how the users of my app can have access to my code and my mlmodel to be able to misuse it, i.e., pass other user's ID to get other user's recommendations.  

On a separate note, but still related, I have not been able to use the recommender mlmodel in my iOS App yet. I have tried both iOS simulator and actual device and I have followed the instructions at https://apple.github.io/turicreate/docs/userguide/recommender/coreml-deployment.html and imported .dylib files but the issue I have opened https://github.com/apple/turicreate/issues/1160 still persists for me. Could you or one of your colleagues please let me know if I am missing something? Or you are working through fixing this or similar issue?

By the way I enjoyed your talk at WWDC very much and thanks again for your time.

**Comment by znation** [comment]
@dogahe The privacy concern is mostly around the app data containing the information for other users than the current user. While it's not straightforward for a typical user to do, a malicious actor could in theory extract information from the app once it's downloaded from the App Store, and if that includes a model that includes user data, they could get access to that user data. (Whereas while you are developing your model, it stays on your machine(s) and isn't downloaded to anyone else.) When a model is queryable by user ID, it necessarily contains the interaction data for the users whose IDs it can be queried for, and we don't expect most app developers would be comfortable shipping that data anywhere.

Another reason we don't include all the user ID mappings in the model is that it greatly inflates the model size; over 50% of the size of a typical Turi Create recommender model is that user data, so by removing the ability to query by user ID, we also produce a much smaller model for use with Core ML.

I'll take a look at #1160 and see if we can get you unblocked there. Thanks for the kind words, and thank you for your time and patience as we sort out these issues!

**Comment by syoutsey** [comment]
Closing this issue as the user guide documents how to use the recommender with a Core ML model.
