### ISSUE TITLE
Turicreate.toolkits._main.ToolkitError: Feature column must contain images

### ISSUE THREAD

**Issue by yashn35** [apple/turicreate#1222]
Hi All,

I have recently been experimenting with the TuriCreate object detection code in which I am trying to write code which can compare my ground truth annotations to what my model has actually predicted. I should then be able to explore this using the turicreate visualization tool.  

This is the code that I am running: 

`
import turicreate as tc

# Load the data
data =  tc.SFrame('/Users/yasnara/Desktop/compost_new_new.sframe')

#Training
# Make a train-test split
train_data, test_data = data.random_split(0.8)

# Create a model

model = tc.object_detector.create(train_data,feature='image', annotations='annotations', max_iterations=110)
model.save('temp.model')

model = tc.load_model('/Users/yasnara/Desktop/temp.model')

model = tc.load_model('/Users/yasnara/Desktop/temp.model')

# Save predictions to an SArray
images = '/Users/yasnara/Desktop/images_new_new'
data['image_with_ground_truth'] = \
    tc.object_detector.util.draw_bounding_boxes(data['image'], data['annotations'])

data['annotations'] = data['annotations'].apply(lambda x: [x])
data['image'] = data['image'].apply(lambda x: [x])

test = tc.SFrame({'image': images})
test['predictions'] = model.predict(test)

test['image_with_predictions'] = \
    tc.object_detector.util.draw_bounding_boxes(test['image'], test['predictions'])
test[['image', 'image_with_predictions']].explore()`

After running this code I get the following error: turicreate.toolkits._main.ToolkitError: Feature column must contain images. 

This error is called from this line: test['predictions'] = model.predict(test). 

I have searched all over the web and have not found any solutions to why this problem is occuring. Please let me know if you have any ideas once you get a chance. 

Best,
Yash

**Comment by shantanuchhabra** [comment]
Hey Yash,

Thanks for using Turi Create! I think you're running into this issue because you are trying to create an SFrame with a column called "image" that has a string (or a list of characters) as the contents. You're probably getting an SFrame with a single column called "image" that has each character of the string `'/Users/yasnara/Desktop/images_new_new'` as the elements of that column, i.e. an SFrame with a single column with a dtype of `char`. 

Instead, assuming the SArray with all the images is saved at `'/Users/yasnara/Desktop/images_new_new'`, you want to do the following: 

```
images_sarray_path = '/Users/yasnara/Desktop/images_new_new'
test = tc.SFrame({'image': tc.SArray(images_sarray_path)})
```

More on the SArray API documentation [here](https://apple.github.io/turicreate/docs/api/generated/turicreate.SArray.html). 

Hope this helps! Feel free to reopen this thread if this doesn't fix your issue or if you run into any other issues!
