### ISSUE TITLE
Object Detector deployed to Vision framework unexpectedly yields confidences at 0.999

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#1314]
I've observed that training and exporting an object detector, and integrating into the Vision sample code [here](https://developer.apple.com/documentation/vision/recognizing_objects_in_live_capture) yields confidences very close to 1. Training and exporting a model with the same data but without NMS yields confidences that span the range from 0 to 1 (after tweaking the sample code just to output the single highest-confidence box).

Our docs describe NMS as a filtering mechanism; we don't expect any "merging" of confidence scores. So there appears to be an error in either the docs, the CoreML implementation, or the Vision integration.

**Comment by jakesabathia2** [comment]
It turns out the issue is not due to non-maximum suppression,
instead it is due to the fact that the sample code for Object Detection provided by Apple
(https://developer.apple.com/documentation/vision/recognizing_objects_in_live_capture)
shows a 'normalized' confidence which enforces scores across all classes sum to 1,
which produce confidence near 1 for the predicted class.
If you want to get the original confidence score for the predicted class,
please refer to VNRecognizedObjectObservation.confidence instead.
