### ISSUE TITLE
Turi For Cats and Dogs Image Classification

### ISSUE THREAD

**Issue by sezan92** [apple/turicreate#137]
I was trying to use turi for cats and dogs image classification. My gpu is nvidia 970 , ram 4GB . i have installed mxnet_cu80 0.11.0 ..but the error comes out to be 

**RuntimeError: simple_bind error. Arguments:
data: (512, 3, 224, 224)
[01:47:51] src/storage/./pooled_storage_manager.h:102: cudaMalloc failed: out of memory**

**Comment by igiloh** [comment]
Hi @sezan92, thank you for trying out the Image Classifier!

I suspect that you run out of GPU memory due to the batch size being statically set to a fixed size of 512. There is already an issue tracking similar incidents of this problem and suggesting a simple solution by exposing the batch_size parameter to the higher-level `create()` API method: https://github.com/apple/turicreate/issues/26.

If you're building turicreate from source, you might try changing the batch_size manually in the [code](https://github.com/apple/turicreate/blob/39da210238b3381c74f6d6a96779fa1637c11255/src/unity/python/turicreate/toolkits/_image_feature_extractor.py#L74).
Otherwise - please stay tuned for a fix.

**Comment by gustavla** [comment]
Hi @sezan92, sorry for the delay in addressing this. Your 4 GB should be more than plenty for the 512 batch size that we use. I suspect that the GPU memory is being used by something else, leaving very little for Turi Create. Can you monitor the memory usage by running `nvidia-smi` and make sure the memory is not used by another process before running your script? Also make sure that you do not import any other package that may allocate GPU memory (for instance, importing `tensorflow` will automatically allocate all GPU memory, so do not import `tensorflow` as part of your script).

**Comment by JiangShj** [comment]
Have you ever solve the problem? I have the same question, Hoping you can give me your solution. Thanks a lot!

**Comment by gustavla** [comment]
@JiangShj Could you look at my last post and report how this looks for you? How does `nvidia-smi` look before and during execution of the script? I recommend running `watch nvidia-smi` to get continuous updates. Also, do you import tensorflow or anything that might implicitly import tensorflow (such as keras)?

**Comment by znation** [comment]
@gustavla Do we have a repro for this issue, or a hypothesis as to how it might repro?

**Comment by gustavla** [comment]
@znation I have repro:ed this with my tensorflow hypothesis above, but I never got a confirmation from 
@sezan92 if this was the problem here. It could be any other process, but tensorflow is a particularly likely one, since that's happened to me.

**Comment by znation** [comment]
@gustavla I see; let's proceed under the assumption that your hypothesis and repro is correct.

**Comment by gustavla** [comment]
@znation OK, then I think we should either close it as it is or possibly look into checking free GPU memory and give the user a better error message if this happens. I think we have to query `nvidia-smi` for this on the CUDA side.
