### ISSUE TITLE
Import image data Error: Unsupported PNG color type: 3

### ISSUE THREAD

**Issue by 0xfeedface1993** [apple/turicreate#138]
This is my image file: [http://oqedp1ccg.bkt.clouddn.com/1xru.png](url)
when I try import image data using **turicreate.image_analysis.load_images()** api,
console show error: 
**Unsupported PNG color type: 3 file: /Users/virus1993/MRD/IMG/captcha_train/1xru.png**
google not helpful, is that mean need translate PNG to JPEG format?
but API document say support PNG, what PNG format support ?

**Comment by igiloh** [comment]
Hi @0xfeedface1993, Thank you for trying out the image analysis toolkit!

The link to your image seems to be broken (or not public). Yet I suspect it might be in RGBA format, which is currently not supported.
Please try the workaround suggested in: https://github.com/apple/turicreate/issues/114#issuecomment-352497812, or if you fail to even load the image try converting it to RGB format first with an external tool.

**Comment by 0xfeedface1993** [comment]
Sorry about image link, here is right one  [image](http://oqedp1ccg.bkt.clouddn.com/1xru.png).
Thanks to your advice, I'm try external tool like PIL:
`>>> from PIL import Image`
`>>> img = Image.open('1xru.png')`
`>>> img`

> <PIL.PngImagePlugin.PngImageFile image mode=P size=300x80 at 0x111A70790>

The image is using sRGB color space (konw by Finder), it is mode P, that will trigger error like

> Unsupported PNG color type: 3

But, try this code to generate new image with mode RGBA:
`>>> Image.open('1xru.png').convert('RGBA').save('1xru.png')`
`>>> img = Image.open('mm/1xru.png')`
`>>> img`

> <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=300x80 at 0x111A708D0>

After that, turicreate.image_analysis.load_images() work just fine.
is RGBA format not support? 
Am I in the right path?

**Comment by gustavla** [comment]
Hi @0xfeedface1993! Thanks for the image, that is really helpful since I am able to reproduce this issue. It looks like we are unable to load PNG images that are saved with an 8-bit palette (that is, a table of 256 colors). Images without color palettes are supported in both RGB and RGBA (RGB + opacity channel), but with RGBA images you can run into issues later (as in #114 with the object detector). Your proposed work-around of using `convert` is a great idea and should work. I would convert it to `'RGB'` though, to make sure you don't trigger #114. I'm really sorry for the inconvenience this is causing!

I will leave this issue open until we have a more permanent fix in place.

**Comment by igiloh** [comment]
@gustavla - I think that in the current state this will be simply a duplication of #114, won't it?
Unless we plan to support also Palette mode in the future.

**Comment by gustavla** [comment]
@igiloh I don't think they are duplicates. It's useful to be able to track the different modes in two separate issues:

* #114: RGBA support
* #138: P support
