### ISSUE TITLE
If it's possible to feed data to the image similarity model by streamline 

### ISSUE THREAD

**Issue by Muggle-Du** [apple/turicreate#1666]
If it's possible to feed data to the image similarity model by streamline instead of load all the images and feed them to the model at one time, since i have a large number of images more than 6GB and it seems impossible to load them to ram at once.

**Comment by Muggle-Du** [comment]
I got a similarity model after training .
I queried the model with some images transformed,rotated for example, from the dataset that i used to feed the model,but the result was not very good .
I mean the image that ranking first was not the original image that i use to transform.

**Comment by TobyRoseman** [comment]
SArrays/SFrame are disk backed data structures. So they can handle datasets which are bigger than the available RAM. You could also just call `query` multiple times.

Can you give us some more information about your use case and how the results are not what you expected?

**Comment by Muggle-Du** [comment]
Thanks  for your quick response. I'll try loading images multiple times.
This is the original picture from my images dataset:
![Man Walk on moon Astronaut New York Times Poster Decorative Posters Room Kraft Poster Wall Sticker Poster Home Bar Decor Gift](https://user-images.githubusercontent.com/25078682/55055781-14c52f80-509f-11e9-9990-d60dc3d7e1e0.jpg)

and this is the image transformed by rotation and adding background:

![ULB86NELJXfFXKJk43Otq6xIPFXaZ](https://user-images.githubusercontent.com/25078682/55055798-1d1d6a80-509f-11e9-80d3-cc6f7aef77e6.jpg)

the similarity model seems not work.

**Comment by TobyRoseman** [comment]
I'm not surprised image similarity isn't performing so well here. Image similarity looks at the entire image as a whole. It works in much [the same way as the image classifier](https://apple.github.io/turicreate/docs/userguide/image_classifier/how-it-works.html) expect instead of creating a classifier (i.e. stage 3) it uses a nearest neighbor model.

I don't fully understand your use case, but [object detection](https://apple.github.io/turicreate/docs/userguide/object_detection/) might be something you want to consider exploring.

**Comment by Muggle-Du** [comment]
thanks , i think i might get it.
Image similarity is not robust enough for rotation and other affine transformations.
I'll try with object detection.
