### ISSUE TITLE
Investigate replacements for MXNet

### ISSUE THREAD

**Issue by nickjong** [apple/turicreate#1678]
Many of our support issues and dependency issues seem associated with MXNet. We should investigate whether an investment in a different underlying deep-learning library would serve us better for CPU training and for Linux GPU. TensorFlow? PyTorch?

**Comment by alkravchenko** [comment]
Hi. As I remember TensorFlow with Metal support demo was shown at WWDC 2018. May be I’m wrong but I hope we can expect public release of it after WWDC 2019 or very soon. Also we have converter from TensorFlow models to CoreML. Now we have alpha version of TensorFlow 2.0 with a lot of improvements. Multi-Level Intermediate Representation (MLIR - https://github.com/tensorflow/mlir) for TensorFlow was also announced. There are TensorFlow forks with AMD GPUs support (but limited though). So for the moment of 2019 year I think that TensorFlow direction is more promising (and has large community). But a lot of things have intermediate or undefined status still. May be everything change next year? Also we have PlaidML from Intel - https://www.intel.ai/plaidml/#gs.7h04gx. It is even support Metal and Keras but unfortunately it didn't work for me (as Keras backend). So I think there are no ideal solutions now. Who can guarantee that TF has less issues count than MXNet for TuriCreate tasks? May be can have several backends at the same time (may be even different backends for different task) with the ability to switch between them (as Keras do)?
Thanks.

**Comment by nickjong** [comment]
FWIW, an update on our end. We are moving forward with switching from MXNet to TensorFlow, for several reasons. The most proximal reason is some deeper incompatibility between the optimizations found in both our code and in MXNet, preventing us from supporting Python 3.7 on some platforms. 

But what we're doing now does move us towards being backend-agnostic, since we already want to support both TensorFlow and Metal at least.

**Comment by ChaiBapchya** [comment]
Hello! @nickjong @alkravchenko This might come in late. But since I see MXNet being used at lot of places still in the codebase I think I can still jump in.

I'm an active contributor to Apache MXNet. It is a worry that there are incompatibilities between MXNet and your optimizations and that we as MXNet community haven't resolved them actively. I am curious to learn more about the same and if there is a way to bridge the gap. At the same time, I want you to know we would try our best to ensure MXnet supports all your required platforms (Linux being one of them).

**Comment by TobyRoseman** [comment]
@ChaiBapchya - Thanks for reaching out. I appreciate it. However we've already began the migration from MXNet to Tensorflow.

We basically have two issues with MXNet. First, all versions of MXNet which support Python 3.7 also require AVX2 support. Second, we were getting regular non-deterministic hangs from MXNet when running on Linux with Python 3.7.

**Comment by TobyRoseman** [comment]
We investigated this and decided to go with Tensorflow. With the release of TuriCreate 6.0 we are now using TensorFlow rather than MXNet.

**Comment by ChaiBapchya** [comment]
>  Second, we were getting regular non-deterministic hangs from MXNet when running on Linux with Python 3.7.

@TobyRoseman @nickjong @alkravchenko 
Are there any issues (on your Github repo or MXNet repo) you can point me to with regards to this "non-determinitic hang", just for our reference. So that we can take it as high priority task to prevent this from happening. As far as I know, we do test MXNet heavily on Python3.7 + Linux (in development phase with CI as well as in production)
But still would be great to know the issue you faced. Thanks
