### ISSUE TITLE
Getting nan after first iteration (object detector)

### ISSUE THREAD

**Issue by fellowProgrammer** [apple/turicreate#1693]
I am trying a to make a CoreML to detect just people. I am using the INRIA dataset. I have tried training this on the CPU instead and it works perfectly fine, but when I use the GPU, after the first iteration I am getting "nan". How can I fix this issue?

**Comment by fellowProgrammer** [comment]
I just tried setting the batch size to 8, 16, 32 all of which are still getting me "nan" after the fist iteration. Although, when I run my python file it always says that it is setting the `batch_size` to 16. I am doing it like this `model = tc.object_detector.create(train_data, advanced_parameters={'batch_size' : 8})`

**Comment by TobyRoseman** [comment]
I don't think that is how you change the batch size. Looking at the [API docs](https://apple.github.io/turicreate/docs/api/generated/turicreate.object_detector.create.html#turicreate.object_detector.create), it seems you want to do:
`model = tc.object_detector.create(train_data, batch_size=8})`. Please try that.

In order to solve the nan issue, it would be helpful to know what operating system you are using.

**Comment by fellowProgrammer** [comment]
Never mind I solved the nan issue by editing the file `turicreate/toolkits/object_detector/_detection.py`, where it says if the computer has less than 4GB of Ram on the GPU than `batch_size = 16`. I changed it to 8 and it works perfectly fine now.

**Comment by nickjong** [comment]
What GPU are you using with Turi Create? How much VRAM does it have?
