### ISSUE TITLE
question: object detection - anchor boxes

### ISSUE THREAD

**Issue by romanoss** [apple/turicreate#1717]
When reading about the yolo model, it is said that one should calculate individual anchor boxes for the own classes. Is this done in turicreate or do you use standard anchor boxes?

**Comment by nickjong** [comment]
Sorry for the inordinate delay in responding to your question! We currently use a fixed list of anchor boxes in all cases. The relative proportions can be seen here: https://github.com/apple/turicreate/blob/21251075e7058c2320e1742059336d5a9e4be174/src/unity/python/turicreate/toolkits/object_detector/object_detector.py#L216

Please feel free to re-open or otherwise follow up if you have any additional questions!
