### ISSUE TITLE
Annotations when column 'annotations' already exists

### ISSUE THREAD

**Issue by srikris** [apple/turicreate#1913]
Overwriting the column called annotations is not a good behavior. 

We should consider the following:
- We can add a '.1', '.2', and so on to the column name
- We can assume the UI state is read from the annotations column so people can annotate only those rows that are new and not annotated

Either way, starting from scratch and wiping out all the existing annotations in not what a user might expect.

**Comment by srikris** [comment]
@znation @abhishekpratapa Thoughts?

**Comment by znation** [comment]
@srikris I'm confused about what you mean by overwriting. The input SFrame should be unmodified. Both the input and newly returned SFrames might contain a column named `annotations`.

I think maybe we could make this clearer to the user by adopting the same convention as `apply`, by making this method return an SArray rather than a whole new SFrame:

```
sa = tc.image_classifier.anntotate(sf)
sf['new_annotations'] = sa # don't clobber
sf['annotations'] = sa # clobber, but explicitly
```

@abhishekpratapa What are your thoughts? Why did we pick SFrame here as the return type, even though we are only ever modifying one column from it?

**Comment by srikris** [comment]
@znation I was referring to the the input frame already contains a column called annotations. Then it mutates instead of adding a new column called annotations.1. Is that expected?

**Comment by znation** [comment]
I think the behavior should always be consistent regardless of what the label column is called. I'll investigate.

**Comment by srikris** [comment]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/1875987/58536243-c74f6680-81a4-11e9-8693-a21741a09d7d.png">

**Comment by srikris** [comment]
Closing because I don't think this is an issue. I misunderstood
