### ISSUE TITLE
Error bundling dylib and pushing to App Store

### ISSUE THREAD

**Issue by erik-cog** [apple/turicreate#2050]
I haven't seen this error elsewhere, has anyone pushed an app to the App Store/TestFlight with a dylib for either the Recommender or SoundClassifier guides? Specifically, when following the [SoundClassifier](https://apple.github.io/turicreate/docs/userguide/sound_classifier/export-coreml.html) guide, I have the libAudioPreprocessing.dylib (v5.6) added to my project, bundling and pushing to devices and running the model as expected. However, I cannot push to TestFlight with the following error:

```
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'QACameraDemo.app/libAudioPreprocessing.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
Return status of iTunes Transporter was 1: ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'QACameraDemo.app/libAudioPreprocessing.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

There are a few references on this issue, in the past it was forbidden to bundle dynamic libraries for security reasons, but in iOS8, apparently this was allowed and it is allowed now in iOS 12. I haven't found anything solid to go on, so if other people have pushed to app store, then I'll at least know its possible. I suspect other people are pushing apps to the app store while containing one of the dylibs distributed via turicreate's releases page. Can anyone confirm whether they've done so?

**Comment by TobyRoseman** [comment]
The code for both the Recommender and Sound Classifier dylib can be found [in this folder](https://github.com/apple/turicreate/tree/master/src/objc). To unblock you, I would try including that code directly in your app.

**Comment by erik-cog** [comment]
Fantastic! Thank you @TobyRoseman

**Comment by TobyRoseman** [comment]
Related #2027

**Comment by erik-cog** [comment]
I'll post back here any pertinent information for others, if there's anything different from the turicreate tutorial needed done to get it to work. I didn't realize the code for the dylib was public too, now I don't have to treat the dylib's mfcc functioning as a black box, which makes me much happier.

**Comment by erik-cog** [comment]
No problems at all. Added the .m and .h files to my project, adding the .m pulled up the dialogue about mixed swift and obj-c and I let xcode create a bridging file. No errors on upload to app store as expected since no dylib this time. Personally I'd recommend this way because its much simpler. There are a number of ways one can screw up adding the dylib (and I can't be the only one who is preternaturally good at finding those ways).

**Comment by TobyRoseman** [comment]
@erik-cog - Thanks for letting us know that worked. Being able to uses these dylib in deployed apps is important. So let's leave this issue open. 

Also now that I have thought more about the workaround, I realize that including the code directly will not be an option for people using the recommender dylib. That code is not self contained like the sound classifier dylib.

**Comment by syoutsey** [comment]
The correct way to bundle a dylib is to wrap it in a framework, detailed in this [technical note](https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-TROUBLESHOOTING_BUNDLE_ERRORS-EMBEDDED__DYLIB_FILES). At a minimum, we need to update our user docs. We should have a larger discussion around shipping a `.framework` instead of a dylib.

**Comment by syoutsey** [comment]
I'm currently trying to determine if we can resolve the App Store submission issues by not embedding the `.dylib` directly but currently having issues with iTunes Connect accounts and uploads to apps within our team. This needs more debugging. If the App Store lets users ship `.dylibs` without embedding them it seems reasonable to just update our user docs to mention this. Otherwise, we'll want to look into modifying our build processes to generate a .`framework` which would require a non-trivial amount of work.

**Comment by JSingh-sol** [comment]
The link to the dylibs is broken "Page not found - Github"

**Comment by TobyRoseman** [comment]
@JSingh-sol - which link are you talking about? You can download the dylibs on our [releases page](https://github.com/apple/turicreate/releases), see the "Assets" section.

**Comment by JSingh-sol** [comment]
@TobyRoseman  : "The code for both the Recommender and Sound Classifier dylib can be found in this folder." <-- the link was broken when I tried it. Nevertheless, I have been getting LibRecommender.zip from the link you provided and I have even tried earlier versions. The screenshots from my early project show that I placed the dylib in the correct spots. I tried a very simple xCode project where all I had was a line to initialize the model when the page loads, ie ' let model = MyRecommender() ' with the dylib placed in the 3 areas mentioned in Apple's instructions. It still did not seem to initialize my .mlmodel because it could not find the TCRecommender. Thank you so much for your continued help and I will also keep trying different solutions as I await your response!

**Comment by TobyRoseman** [comment]
@JSingh-sol - we recently did some code reorganization [here is the the updated link](https://github.com/apple/turicreate/tree/master/src/deployment).

**Comment by JSingh-sol** [comment]
@TobyRoseman Thank you so much but bare with me, I am an intern and have a tendency to miss the obvious. How do I incorporate your solution to my existing project?

So the link takes me to the following files on Github:
 
<img width="1013" alt="Screen Shot 2019-07-22 at 6 01 09 PM" src="https://user-images.githubusercontent.com/51454748/61670853-c7527b00-acaa-11e9-8490-9475eb54b3ff.png">

But I thought my issue was with the .dylib file, so how should I implement these newly configured files. Again, thank you so much!

**Comment by JSingh-sol** [comment]
I previously imported Turicreate 5.4 on a python script to create a custom model on Google Colab or Jupyter notebook, export it as a .mlmodel and then integrate with my project. How exactly can I use these files?

**Comment by TobyRoseman** [comment]
@JSingh-sol - it sounds like you're using the recommender dylib. So using these source files directly is not an option for you. That dylib is not self contained like the sound classifier dylib. To unblock you we'll need to resolve #2148.
