### ISSUE TITLE
Questions Regarding Content Based Recommendation

### ISSUE THREAD

**Issue by dogahe** [apple/turicreate#2054]
I am working on a Recommendation System that is based on content of let say articles. We can  assume they are news articles that have several fields, for example, "Article ID", "Title", "Short Abstract", "Full Text". I have a few questions about best practices or recommendation from you on how I am supposed to go about this problem: 

1. Let say I would like to decide which fields out of the available fields ("Title", "Short Abstract", "Full Text") should I use for this purpose as features, because for my dataset, not all the fields (e.g., "Title", "Short Abstract") are available for all articles? Should I just use "Full Text"? Or using "Title" and "Full Text" will give me better performance? Also, if I use all the available fields is there a way to either impose importance weights, or know the importance weights (after model is trained) of each feature?
2. I am using `.item_content_recommender.create` with no usage data, and therefore no UserID field is provided in the training data since I am looking at a pure content based recommendation. After the model is trained I cannot use `metrics = model.evaluate(test)` because I get this error: `AssertionError: Provided data set must have a column pertaining to user ids and              item ids, similar to what we had during training.` How can I get metrics on how the model performs?
3. After the model is trained, and I am using it for recommendations as in `recommendations = model.recommend_from_interactions(['ArticleID 12'])`, if I have used "Full Text" as the feature, it's hard to see why the recommended articles are similar to Article 12. Is there a way to get a list of top `2-Word NGram Counts -> TFIDF` ( since the model said that's what it used) between Article 12 and what's recommended for Article 12 as similar?

**Comment by hoytak** [comment]
Hey @dogahe, 

Using the item content recommender is admittedly a bit tricky.  I'm not really happy with it's overall performance and the amount of general tweaking required to get it working, and I wrote it. 

Currently, the method uses a bunch of heuristics to build a graph of what items are similar to which other items.   The distance between two items is a weight of the distances between the individual columns of the items, with the weights determined by another heuristic -- essentially the distances are weighted so that average weighted distance between all column pairs equals 1, i.e. all columns have approximately equal weight.  I'm not sure how to get these base weights, but you can supply additional weights to scale each column if you want.  Ideally, these weights should be learned, but that's not a feature we've implemented yet. 

2 is a bug.  

So, given your use case, I would recommend a bit more detailed of a process.  The same process as the item_content_recommender does under the hood (See https://github.com/apple/turicreate/blob/master/src/unity/python/turicreate/toolkits/recommender/item_content_recommender.py) can be done explicitly with the nearest neighbors toolkit, and that can be used to create a graph of item similarities by querying the model with the same data used to build it.  With that, that graph can be passed into the item_similarity_recommender using the nearest_items parameter, in which case the user -item table can just be an empty SFrame with the appropriately named columns.  This can then essentially replicate the entire item_content recommender, but give you much more control over the task.
