### ISSUE TITLE
request column order in sframe to be deterministic.

### ISSUE THREAD

**Issue by Jarvi-Izana** [apple/turicreate#2129]
#2121 requires the column orders to be deterministic so that the user can provide their name resolution by assuming the order columns appear in SFrames before hand.

Currently, If we construct SFrame from dicts or associative data sturctures, the order of column names is non-deterministic.

A possible solution is sorting the column names.

**Comment by Jarvi-Izana** [comment]
I just figure out an easy way to make #2121 order-independent. Either way works for me. Just let me know if it's necessary to make column order deterministic.

**Comment by hoytak** [comment]
Closing for now; behavior resolved by #2121.  Let's not make this change without a compelling reason.

**Comment by TobyRoseman** [comment]
@hoytak - this issue is not resolved by #2121. That issue is the reason we created this issue.

In my opinion, allowing code to be deterministic is a more than compelling enough reason to make this change. What are the concerns about making this change? 

It seems very low risk to me. I think the change would be something like getting all the key/column-names, sorting them, then just creating the columns (as usual) in that order.

**Comment by Jarvi-Izana** [comment]
@TobyRoseman I have a new push to #2121, which requires resolution operation to be order-independent. I think If we have a compelling reason to make it deterministic in the future, we can do it then.

**Comment by hoytak** [comment]
This isn't really a needed feature, given that this is due to the python dict key order.  If this is common, .  It would also be (minorly) API breaking.  Closing now unless there is a compelling reason to change the current behavior.
