### ISSUE TITLE
Using TuriCreate with Poetry

### ISSUE THREAD

**Issue by dogahe** [apple/turicreate#2269]
I am using [Poetry](https://poetry.eustace.io) for Python Package management. Simply I started a new Poetry project (poetry-turicreate) by doing:

`poetry new poetry-turicreate`
`cd poetry-turicreate`
and when I do:

`poetry add turicreate`

I get the following error:

```
Creating virtualenv poetry-turicreate-py3.7 in 
...Library/Caches/pypoetry/virtualenvs
Using version ^5.7 for turicreate

Updating dependencies
Resolving dependencies... (0.1s)
                                               
[TypeError]                     
can only concatenate str (not "int") to str ```

**Comment by TobyRoseman** [comment]
Looks like there are two issues here. One is a TuriCreate issue and one is a Poetry issue.

The first issue is that TuriCreate has transistive dependency requirements that can not be satisfied. For one reason or another this has been the case for quite awhile. We are tracking the most recent issue causing it in #2249.

The second issue is a Poetry issue. When constructing an error message for the above issue, Poetry tries to concatenate a `str` and a `int`. This can be seen by running: `poetry add -vvv turicreate` rather than just `poetry add turicreate`.

I suggest you open an issue or pull request with Poetry. Given the stack trace it should be easy to fix.

Please note: that when/if Poetry fixes their issue, you still will not be able to use TuriCreate with Poetry, because Poetry requires all dependencies to be satisfied.

Since we're already tracking the TuriCreate issue in #2249, I'm going to close this issue.
