### ISSUE TITLE
'tuple' object has no attribute 'column_names'

### ISSUE THREAD

**Issue by GaneshKumarSelvam** [apple/turicreate#2301]
Im new to Python while inserting images in DB, why am I getting this error, how can we solve this issue.

File "/usr/local/lib/python3.6/site-packages/turicreate/toolkits/image_classifier/image_classifier.py", line 242, in create
    if target not in dataset.column_names():
AttributeError: 'tuple' object has no attribute 'column_names'

**Comment by TobyRoseman** [comment]
Hi @GaneshKumarSelvam - it looks like you are calling `tc.image_classifier.create` and passing a tuple rather than an SFrame for the `dataset` parameter (i.e. the first parameter). You need to [create and SFrame](https://apple.github.io/turicreate/docs/userguide/sframe/sframe-intro.html) with your data then pass that to `tc.image_classifier.create`.

Take a look at our user guide for more information about [creating an image classifier](https://apple.github.io/turicreate/docs/userguide/image_classifier/).

I'm going to leave this issue open until we have a better error message in place. We should be checking the type of `dataset` before we call `dataset.column_names()`.
