### ISSUE TITLE
turicreate.load_audio broken with home directory present.

### ISSUE THREAD

**Issue by hoytak** [apple/turicreate#2685]
The following code generates a dataset that has no entries: 

```
In [13]: import turicreate as tc
    ...:
    ...: data = tc.load_audio("~/data/ESC-50/audio/")
```

However, the same code where the ~ is replaced by the absolute path name works fine.

**Comment by TobyRoseman** [comment]
A `~` in the path also doesn't work with `tc.load_images`. It does however work for `tc.load_sarray` and `tc.load_sframe`.

**Comment by TobyRoseman** [comment]
A `~` also works in the path for `tc.load_model` and `tc.load_sgraph`. So this just needs to be fixed in `tc.load_audio` and `tc.load_images`.

The functions that do this properly all seem to use the [_make_internal_url](https://github.com/apple/turicreate/blob/6709d22b2a904aafad7f93ac10d4762d75e60020/src/python/turicreate/util/__init__.py#L99) method. It seems like using this will also fix other issues too (e.x. S3 paths).
