### ISSUE TITLE
Stylize on one image with multiple styles does not seem to work (no crash)

### ISSUE THREAD

**Issue by shreyajain17** [apple/turicreate#2723]
```
result = model.stylize(content['image'][0])
result.explore()
```

**Comment by syoutsey** [comment]
@shreyajain17, what is the expected and actual behavior here?

**Comment by abhishekpratapa** [comment]
Its a silly bug where the first style is always used to stylize the images in predict. The correct behavior would be to set the correct style number in predict before stylizing the image.

Since we didn't define a way of changing the index in MPS this is the behavior we have. The fix would be to set this index variable before the call to predict in MPS.

**Comment by shreyajain17** [comment]
Could it be done `style_transfer.cpp` before MPS? I can look into it if that is the case.
