### ISSUE TITLE
Why csv files always takes user_id and item_id

### ISSUE THREAD

**Issue by Padalingam** [apple/turicreate#283]
i wanna use two different csv file for users and movies. i have two columns called user_id and movie_id. when i run movies.csv file i got the following error.
**Error**
Finished parsing file /Users/padalingam/Documents/Xcode 9 Projects/Movie-Rating/MovieRecommendation.csv
Parsing completed. Parsed 6233 lines in 0.023191 secs.
Recsys training: model = item_similarity
[ERROR] turicreate.toolkits._main: Toolkit error: Column name user_id does not exist.
Traceback (most recent call last):
  File "sample.py", line 4, in <module>
    m = tc.item_similarity_recommender.create(datacsv)
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/recommender/item_similarity_recommender.py", line 258, in create
    response = _turicreate.toolkits._main.run('recsys_train', opts, verbose)
  File "/Library/Python/2.7/site-packages/turicreate/toolkits/_main.py", line 84, in run
    raise ToolkitError(str(message))
turicreate.toolkits._main.ToolkitError: Column name user_id does not exist.

**Comment by TobyRoseman** [comment]
@Padalingam - I do not have enough information to debug the issue.

From the stack trace it sounds likes the item similarity recommender can't find the user id column. This could be because that information is not present in your SFrame. Or maybe that column is called something other than `user_id`. Using the `user_id` parameter you can specify a different column name value. Here is the `item_similarity_recommender.create` API:
https://apple.github.io/turicreate/docs/api/generated/turicreate.recommender.item_similarity_recommender.create.html#turicreate.recommender.item_similarity_recommender.create

If this doesn't help, please reopen and include the code that you are using.
