### ISSUE TITLE
context information incorporation for recommenders 

### ISSUE THREAD

**Issue by dirtyoneweek** [apple/turicreate#2977]
Hi,

### Requirements
I'm trying to incorporate context info (e.g. where/when a user interacted with an item) to the recommender, and I'm referring to this doc https://apple.github.io/turicreate/docs/api/generated/turicreate.recommender.ranking_factorization_recommender.create.html.

### Question
Although **_user_data_** and **_item_data_** args allow to add some types of side info, they don't seem to allow the incorporation of side info that corresponds to a (_user, item_) pair. That is to say, if my training samples are triples, [ _(user1, item2, context2),  (user2, item2, context1), (user2, item2, context2)_, ...], the context feature cannot be represented as  either  **_user_data_** or **_item_data_**. Did I miss something?

@hoytak

**Comment by hoytak** [comment]
Hello @dirtyoneweek, 

Yes, that is correct -- the side information there is not associated with the observation, only the user or the item.  Unfortunately this is a bit of a difficult problem in general, and there are tricks to get around it.  Could you tell me more about your data?  Approximately how many users / items / observations do you have, and how much side information do you have that you think would be relevant?

**Comment by dirtyoneweek** [comment]
Hi @hoytak,
The dataset is quite "imbalanced". I'm having 2 million users, 60 items and around 10 million observations. 

The side info is complex. There are different types of side info including: timestamp for each observation, product specs for each item, demographic info for each user, etc.. And more importantly, we have several other types of user/item interactions in addition to the observations, such as when/where/how the users use the items after purchase. We're still experimenting on different side info, not sure how much will be relevant yet.

I see Factorization Machine (_Steffen Rendle, “Factorization Machines,” in Proceedings of the 10th IEEE International Conference on Data Mining (ICDM), 2010._) is in your references. And based on my understanding, any side info (including context info) can be incorporated into a CF model if using FM. So it made me confused when I found it didn't support context info incorporation.

**Comment by hoytak** [comment]
It can be incorporated with this model, but the issue is that the optimization to train it can be extremely hard and the resulting model can be extremely finicky.  We could never get it working reliably in production -- it was way too sensitive.  

In your case, you're lucky with having only 60 items. I would actually treat this as a multiclass classification problem.  Set the problem up like this:

For each observation, have as features: 
1. A binary vector of 0s and 1s indicating which items other than the observed item that the user interacted with.  In TC, this can be done as a categorical list of strings e.g. ["item1", "item5", "item45"] . If there are ratings there, use a dictionary instead.  This is how the user data is encoded. 
2. All the relevant side information. 
3. The target class would be the item the user interacted with. 

I would trial run this with logistic_classifier, then the boosted_trees_classifier would give you the best accuracy. 

Then, on prediction, get the probability_vector type output, zero out all the items the user has interacted with, and rank recommendations by probability.

**Comment by dirtyoneweek** [comment]
@hoytak Sorry for the late reply. Really appreciate your good suggestion. It looks quite "different" somehow but very interesting. We actually tried it. Here are the findings and thoughts:

1. Yes, indeed, the context info now can be incorporated in this way, but it's more like viewing it as a common classification problem and it loses the advantage of efficiently modeling 2-order or higher order feature interactions like Collaborative Filtering/ Factorization Machine does. It's actually totally fine , just making me curious if it'll be better using vanilla Factorization Machines.

2. For the first point you make, we did try your suggestion by modeling user with the list of his purchased items. But we didn't find any performance improvement compared to simply modeling user with a categorical variable. The only advantage I can see is it can help reduce the number of coefficients. Any other reason?

3. Viewing the problem as multi-class classification instead of binary is very interesting. I really  For me, the greatest advantage is you don't need to worry about negative sampling from the unobserved, which will be quite complex if the model includes context info. Is it why you suggested doing this?
