### ISSUE TITLE
libRecommender in release bundle is labeled as x86_64 but seems to be compiled for arm64 

### ISSUE THREAD

**Issue by danielgronlund** [apple/turicreate#3075]
I'm building a Mac app with a recommender model. But the libRecommender downloaded from the release section (release 6.1) doesn't seem to include a proper x86_64 binary.

The build log is showing that the compiler is ignoring the linking:
![build log](https://user-images.githubusercontent.com/1548127/77848773-86aaea00-71c7-11ea-897c-f4eadf06a571.png)

Lipo output of the framework binary:
![Skärmavbild 2020-03-29 kl  14 13 19](https://user-images.githubusercontent.com/1548127/77848790-9e826e00-71c7-11ea-9376-0306a55dd4b0.png)

The symptoms are same as in this issue: https://github.com/apple/turicreate/issues/2148

**Comment by TobyRoseman** [comment]
@danielgronlund - I've confirmed this issue. Sorry about this. It's my fault. I must have mixed up the x86_64 and arm64 files that are named the same thing when I was packaging the `libRecommender.zip` release artifact. This issue is related to #3004; we need to automate this release process in order to prevent these types of errors.

Here is a recent [artifacts.zip](https://github.com/apple/turicreate/files/4405998/artifacts.zip) generated from master. It contains the x86_64 dylibs for both the Recommender and the Sound Classifier

**Comment by TobyRoseman** [comment]
@danielgronlund - thanks again for pointing out this issue. This has been fixed in our last two releases. I'm going to close this issue.
