### ISSUE TITLE
Review "GPU Support" Documentation

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#3124]
I don't think the [GPU Support Section](https://github.com/apple/turicreate#gpu-support) of our top level README is up to date.

- [x] Verify all of the min macOS version listed there are accurate. 
- [ ] Verify that "discrete GPU only" information is still accurate.

- [x] List info for One Shot Object Detector.
- [x] List info for Sound Classifier.
- [x] List info for Drawing Classier.
- [x] List info for Style Transfer.

- [ ] Clarify that we only ever use one GPU.

**Comment by tagy** [comment]
With turicreate 6.1 in Ubuntu with a GPU, I have to run this command after booting my pc:

export TF_FORCE_GPU_ALLOW_GROWTH=true

Otherwise I get a memory crash as soon as I start training. It seems to be common problem people hit with tensorflow. When using tensorflow directly there is a way set this in the configuration but I could not see how to that via turicreate. More here: [https://stackoverflow.com/questions/43843208/is-it-possible-to-make-allow-growth-true-set-by-default-in-tensorflow](https://stackoverflow.com/questions/43843208/is-it-possible-to-make-allow-growth-true-set-by-default-in-tensorflow)

I don't know if this is helpful to anyone, but I spent a long time resolving this.
