### ISSUE TITLE
How is decision tree classifier leaf value associated with the probability?

### ISSUE THREAD

**Issue by boaloysius** [apple/turicreate#3224]
Hi, I have created a decision tree classifier.
On parsing the decision tree using model._get_tree().to_json() I found few leaf values have negative value.

Qn
1) How do I interpret the negative value in leaves?
2) How do I convert it to leaf value to score?
3) What is the default value of the probability threshold used to find precision and recall?

Thank you

**Comment by boaloysius** [comment]
in question 2, by score I meant probability.
How do I convert it to leaf value to probability?

**Comment by hoytak** [comment]
Hello @boaloysius, 

The scores on the leaves of each tree are added together, then transformed through a sigmoid function, i.e. `1 / (1 + exp(-x) )`.  This sigmoid function maps a score of 0 to probability 0.5 and all the results are between 0 and 1. 

Now, the probability threshold is set to 0.5, though the "probability" can be affected during training by adjusting the class weights at training time, so in that sense it's not really a true probability as the training can be biased one way or the other.  To do your own PR curve, though, you can have the predict() function output the raw probabilities instead of just a class prediction and threshold it yourself.

**Comment by TobyRoseman** [comment]
@boaloysius - I'm going to close this issue but let us know if you have any follow up questions.
