### ISSUE TITLE
SyntaxError: invalid syntax (while Installing on python 3.8.1 on linux)

### ISSUE THREAD

**Issue by actcod01** [apple/turicreate#3241]
`1. pip3 install turicreate 
`
****
![image](https://user-images.githubusercontent.com/67143298/86129828-ee433f00-bb00-11ea-801b-ba2eef283497.png)

**Comment by TobyRoseman** [comment]
TuriCreate does not yet support Python 3.8. We do support 2.7, 3.5, 3.6 and 3.7 on Linux.

@actcod01 - I think there is an issue with your Python environment. Based on the screenshot you shared, it looks like you are actually using Python 3.5: note the `cp35-cp35m` in the whl filenames for `turicreate` and `llvmlite`. `pip3` is failing when it tries to install one of TuriCreate dependencies. That dependency is pandas, which has recently dropped support for Python 3.5. For some reason `pip3` is failing because it is trying to install the most recent version of panda (which doesn't support 3.5) from source. Try running: `pip3 install --prefer-binary turicreate`

We are already tracking TuriCreate support for Python 3.8 in #3099. I'm going to close this issue as a duplicate, but let me know if you have more questions.
