### ISSUE TITLE
When should one consider Turi Create instead of Scikit learn/Tensorflow etc..

### ISSUE THREAD

**Issue by theobouwman** [apple/turicreate#3250]
When should one consider Turi Create instead of Scikit learn/Tensorflow etc..?

**Comment by TobyRoseman** [comment]
I think there are several reasons someone might choose to use TuriCreate rather than another tool. Below are what I see as the three largest reasons. 

1 - **Ease of use**. Turi Create is designed to simplify the development of custom machine learning models. It aims be the easiest way to add Machine Learning to your app. Hopefully in as few as five lines of code. Our [Task Focused Toolkits](https://apple.github.io/turicreate/docs/userguide/applications/) are particularly easy to use. Our lower level toolkits also try to do as much as possible for you. For example one hot encoding and dictionary vectorization are handled for you by TuriCreate. With most other tools you need to do this yourself.

2 - **Work with large dataset on your laptop**. TuriCreate make wide use of [SFrames](https://apple.github.io/turicreate/docs/api/generated/turicreate.SFrame.html), a tabular dataframe which is disk backed, so it scales to "Big data". Our toolkits are built on top of SFrame which mean you can create machine learning models using a dataset larger than the size of your RAM.

3 - **Export to Core ML**. Most models created by TuriCreate can be exported to [Core ML](https://developer.apple.com/documentation/coreml); you can easily deploy most TuriCreate models to any Apple device.

@theobouwman - I'm going to close this, but let me know if you have any additional specific questions.
