### ISSUE TITLE
Input image format for ObjectDetector(Darknet-YOLO)

### ISSUE THREAD

**Issue by rdv0011** [apple/turicreate#3256]
In what format TuriCreate model expects an input image? Particularly I am interested in bias and a scale value. For example in CoreMLTools in some cases these parameters are specified explicitly:
```c
is_bgr: you typically need to set this to True for Caffe models
red_bias, blue_bias, green_bias: these will be added to the R, G, and B color values of each pixel
gray_bias: like the RGB biases but for grayscale images
image_scale: the pixel values will be multiplied by this number.
```
I wonder if something similar needs to be specified for TuriCreate for ObjectDetector(Darknet-YOLO(object detector))

**Comment by TobyRoseman** [comment]
TuriCreate uses its own image format. These can be created, from JPEG or PNG files, by calling [tc.load_images](https://apple.github.io/turicreate/docs/api/generated/turicreate.load_images.html).

In order to create an object detection model (using Darknet-YOLO) you do **not** need to manually scale or add a bias to your images. See our user guide for [an example of creating an object detector](https://apple.github.io/turicreate/docs/userguide/object_detection/).
