### ISSUE TITLE
Object detector model `turicreate.object_detector.create` doesn't allow periodical saving of models before the training is over.

### ISSUE THREAD

**Issue by NeerajKomuravalli** [apple/turicreate#3286]
I have been using turicreate's object detector model for a while now and what I have noticed is that it doesn't let me save models after every n iteration while the training is going on. 
I believe this is a very important feature to have as sometimes for a lot of reasons (hardware or software or other unpredicted reasons) the training gets killed and when it exits I don't even have a model which one might have spend hours training. 

I believe this part of the code is written in C++ and I am not that great with c++ but If pointed in the right direction I can pick this up and add this feature or if someone more experienced can pick it up that will be great too.

**Comment by TobyRoseman** [comment]
This is the same feature request as #574.

@NeerajKomuravalli - [Here is the main training loop for object detection](https://github.com/apple/turicreate/blob/7b6b72a7e0302788dfc857841ebbc5bf572ab7e4/src/toolkits/object_detection/object_detector.cpp#L359). Since we already have an open issue for this feature request, I'm going to close this issue. However feel free to ask any additional questions here.
