### ISSUE TITLE
Image similarity takes too much memory

### ISSUE THREAD

**Issue by duchaomin** [apple/turicreate#3321]
Image similarity uses too much memory. I have 1 million pictures with 800* 800 pixels to do  image similarity  and the memory usage is 120GB. How can i to decrease it?

**Comment by TobyRoseman** [comment]
Much of that memory is probably just the images themselves. Try first extracting the deep features from the images. Then before creating the model, allow the memory for those images to be garbage collected.

Also try using a squeezenet backed model, rather than the resnet default. It will have smaller deep features and also a smaller neural network.

If your SFrame is called `sf` and your image column is called `image`, you would want to do the following:
```python
sf['deep_features'] = tc.image_analysis.get_deep_features(sf['image'], model_name="squeezenet_v1.1")
del sf['image']    # allow images to be garbage collected
model = tc.image_similarity.create(sf, feature='deep_features', model="squeezenet_v1.1")
```

**Comment by duchaomin** [comment]
Many thanks. I will try it.

**Comment by TobyRoseman** [comment]
I'm going to close this issue. Let us know if you have any more questions.

**Comment by duchaomin** [comment]
No more questions, thanks
