### ISSUE TITLE
Turicreate with TensorFlow 2.3?

### ISSUE THREAD

**Issue by mxlei01** [apple/turicreate#3368]
I'm trying to install tensorflow 2.3 along with turicreate, but I'm getting into an issue:

```
 The user requested tensorflow==2.3.0
    turicreate 6.4 depends on tensorflow<2.1.0 and >=2.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

Will turicreate upgrade tensorflow to 2.3 in the near future? I see that there aren't a lot of code commits recently, will there be ongoing support for this package or will people need to move to another package like vaex for out of core support?

**Comment by TobyRoseman** [comment]
TensorFlow 2.3 is currently supported on macOS. So I assume you are using Linux. Let me know if that's not correct.

The reason we do not support TensorFlow 2.3 on Linux is due to a change in TensorFlow which breaks our Sound Classifier, see #3303 

If you're not using the Sound Classifier, then TuriCreate should work fine for you with TensorFlow 2.3. You can just install that version of TensorFlow manually after installing TuriCreate.
