### ISSUE TITLE
SArray .sum() is time-consuming

### ISSUE THREAD

**Issue by ChujieChen** [apple/turicreate#3402]
I have an SFrame with shape
```
products.shape   # (183531, 15)
```

`products['awesome']` is just an SArray of int. I want to have the sum of all values with

```
%time products['awesome'].sum()
```
gives me
```
CPU times: user 20.1 s, sys: 1.97 s, total: 22.1 s
Wall time: 8.92 s
Out[43]:
4075
```

**Comment by TobyRoseman** [comment]
SFrame and SArray are lazily evaluated. If it's taking a long time for `sum` to return, that's probably because `sum` is forcing evaluation of other things which haven't actually been computed yet. 

You can force thing to be evaluated by calling `materialize()`. Try calling `products.materialize()`, right before calling sum. I would expect the `materialize` call to take almost all of the ~9 seconds you're seeing. Then `sum` should return very quickly.

**Comment by ChujieChen** [comment]
> SFrame and SArray are lazily evaluated. If it's taking a long time for `sum` to return, that's probably because `sum` is forcing evaluation of other things which haven't actually been computed yet.
> 
> You can force thing to be evaluated by calling `materialize()`. Try calling `products.materialize()`, right before calling sum. I would expect the `materialize` call to take almost all of the ~9 seconds you're seeing. Then `sum` should return very quickly.

Oh, that makes sense. It works. Thanks!
