### ISSUE TITLE
LaTeX equations not rendering properly

### ISSUE THREAD

**Issue by burczyk** [apple/turicreate#388]
I was reading the docs and noticed that LaTeX equations are not rendering properly, probably due to lack of support for this feature on GitHub. It can be seen e.g. in this document: https://github.com/apple/turicreate/blob/master/userguide/supervised-learning/knn_classifier.md
Is there a walk around? 
If LaTeX is not supported maybe these equations should be prerendered and placed as images?

**Comment by gustavla** [comment]
Ah, good catch, that does look ugly viewed through GitHub. You can view the user guide with the correct latex rendering here though:

https://apple.github.io/turicreate/docs/userguide/supervised-learning/knn_classifier.html

Perhaps we should discourage GitHub browsing of the user guide because of this?

Just curious, how did you end up reading it on GitHub as opposed to the rendered version at apple.github.io?

**Comment by znation** [comment]
@gustavla I think the GitHub version is more obvious than the rendered documentation link. It's called `userguide` in the root of the repo.

Unfortunately there's really no way to render LaTeX math on GitHub itself (because we can't load external script), and the closest thing I can find to an issue on it for GitHub is [closed](https://github.com/github/markup/issues/897).

I don't think we should change where the userguide is stored (in the `userguide` directory at the top level), and usually it's fine to browse the user guide that way (sometimes, more convenient, especially if you want to edit inline without cloning the repo).

For those who want to see math rendering in all its glory, please visit https://apple.github.io/turicreate/docs/userguide/ .

**Comment by burczyk** [comment]
@gustavla I simply opened main repository GitHub page (https://github.com/apple/turicreate) then wen to [Classifiers](https://github.com/apple/turicreate/blob/master/userguide/supervised-learning/classifier.md) and [Nearest neighbor classifier](https://github.com/apple/turicreate/blob/master/userguide/supervised-learning/knn_classifier.md).
I didn't browse it manually from `userguide` but ended up there anyway 🤷‍♂️

**Comment by igiloh** [comment]
hmmm - @znation I wonder if we might need to change the links in the readme files to the rendered version of the UG and API doc?

**Comment by znation** [comment]
@igiloh I didn't notice any links that go directly to the userguide source (as opposed to apple.github.io) - but if you find any, please feel free to put up a PR that moves them to the rendered HTML version.

**Comment by igiloh** [comment]
@znation The very ones that @burczyk mentioned, right [here](https://github.com/apple/turicreate/blob/master/userguide/supervised-learning/classifier.md#classification)

**Comment by znation** [comment]
@igiloh Those are internal links within the userguide - that page itself should also have been a link to apple.github.io (and if/when it is, the internal links will work). I don't think we should change all the internal (relative) links within the userguide to be absolute links; it'll make it much harder to build/test the userguide locally and make edits. The question is: how did you get to that page in the first place? Is there a link from outside the userguide that we can modify to point to the rendered HTML version instead?

**Comment by igiloh** [comment]
@znation - sorry, wrong link.
I've meant the ones in the bottom of [this section](https://github.com/apple/turicreate/blob/master/README.md#example-image-classifier-with-a-few-lines-of-code) of the main readme file.

**Comment by znation** [comment]
@igiloh Thanks! Fixed in #407.
