### ISSUE TITLE
Access YOLO model from object detection

### ISSUE THREAD

**Issue by smahurkar** [apple/turicreate#537]
Is there a way to access the retrained darknet YOLO model files after training object detection with Turicreate?

**Comment by gustavla** [comment]
Hi @smahurkar! What do you mean by accessing the retrained darknet YOLO model? Do you mean accessing the model weights specifically?

If you mean the weights, there is unfortunately no easy and documented way of doing this.

**Comment by smahurkar** [comment]
I meant getting the weights and config files after the training. 

I was hoping to use the trained object detection model on other platforms besides iOS (Android and Web). Is there a way to export models from Turicreate to Tensorflow/Darknet models?

**Comment by gustavla** [comment]
I have not tested either of these packages, but this package claims Core ML -> ONNX: https://github.com/onnx/onnxmltools
After that, the description of this one suggests it can do ONNX -> TF: https://github.com/onnx/onnx-tensorflow

Again, I can't guarantee success because I haven't tried it, but hopefully it's a starting point. I'll close this issue, but please feel free to add more information here for others to see if you figure it out. Thanks!

**Comment by zoecarver** [comment]
I tried this without success.

**Comment by dhgokul** [comment]
@zoecarver did you tried this ?  
I tried this, can able to convert coreml to onnx, but when convert from onnx to tf , i got issue

**Comment by zoecarver** [comment]
Nope, sorry.
