### ISSUE TITLE
My exported trained model returns wrong predictions once in Core ML format

### ISSUE THREAD

**Issue by zeparedes** [apple/turicreate#582]
After successfully training a Boosted Trees Classifier model and then exported to a Core ML model and imported it into a Xcode project all processes worked well but the predictions from the converted model comes out wrong

Here is the training data set 
[fullHori.txt](https://github.com/apple/turicreate/files/1983855/fullHori.txt)

Model creation
data    = tc.SFrame.read_csv('fullHori.csv')
model = tc.boosted_trees_classifier.create(data, target='shapes')
model.export_coreml("shpModel.mlmodel")

Model test with coremltools
model =  coremltools.models.MLModel('shpModel.mlmodel')
pred   = model.predict({'a': 0.0511, 'b': 0.0564, 'c': -0.0632, 'd': 0.0492, 'e': 0.1657, 'f': -0.0499, 'g': 0.0528, 'h': 0.2515, 'i': -0.0512, 'j': 0.0, 'k': 0.0, 'l': 0.0})

**Comment by srikris** [comment]
@zeparedes Thanks for reporting things. We will investigate this.

**Comment by zeparedes** [comment]
Just wondering if I can help in any way, just let me know I’ll be happy contributing

**Comment by hoytak** [comment]
We have updated several issues with this previously, but usually these issues boil down to numerical inaccuracies that are next to impossible to prevent.  The main reason is that the boosted trees model often uses values from the training dataset in determining the split points.  At these specific values, calling the models at these specific values can often give a different prediction.  

The reasons for this are usually due to two things. First, the training is done with float32, but predictions in CoreML are done with float64, and minor differences in the numerical values cause the model to go down different branches, and these different branches will have different predictions.  Second, converting from decimal values to float32 or float64 (e.g. reading from a CSV file, giving it explicitly, etc.) will produce slightly different numbers.  In other words, each of the following routes can be a different number:  decimal->float64, decimal->float32, decimal->float64->float32, float64->float32, etc.  As a result, if the original value was present in the training data, each of these paths may give a different prediction.  Thus, when testing boosted tree model export, it's very difficult to use values from the training data.

**Comment by hoytak** [comment]
This issue is a bit deeper.  Working on a fix.

**Comment by hoytak** [comment]
Fixed with https://github.com/apple/turicreate/pull/958
