### ISSUE TITLE
Incorporating new observation data

### ISSUE THREAD

**Issue by AdamMiltonBarker** [apple/turicreate#63]
Does this actually train the new data to the model or is it only passed to reference ?

**Comment by srikris** [comment]
@AdamMiltonBarker Could you clarify your question some more?

**Comment by AdamMiltonBarker** [comment]
Hi @srikris thanks the quick reply, so regarding the docs on new observation data:

> recommend() accepts new observation data. Currently, the ItemSimilarityModel makes the best use of this information.

```
m_item_sim = turicreate.item_similarity_recommender.create(data)
new_obs_data = turicreate.SFrame({'user_id' : ['Charlie', 'Charlie'],
	                        	'item_id' : ['Item1', 'Item5']})
recommendations = m_item_sim.recommend(['Charlie'], new_observation_data = new_obs_data)
```
Does this actually update the net with the new observation data, or is it just used to reference against and is then gone when the recommendation finishes? If this is the case, is there a way to train the network with new data but not have to retrain the entire network again from scratch, so I am describing online learning, but some people call it other things.

**Comment by srikris** [comment]
Sorry for the late response. No it does not update the data but it updates the predictions assuming this new data was seen so the effect is pretty close.

**Comment by mappls** [comment]
To add to the question of @AdamMiltonBarker, since the `new_observation_data` doesn't update the model, what would be the recommended way to implement "online" updating of the model with new data?

Re-training the model from scratch, every once in a while, simply wouldn't work in real system, so we need a way to gradually update the learned weights & factors with new data samples.
