### ISSUE TITLE
median in int column in SFrame summary not correct

### ISSUE THREAD

**Issue by afranklin** [apple/turicreate#689]
Import turicreate as tc
sf=tc.SFrame({'A':[1,2,3,4],'B':['a','a','b','b']})
sf.show()

Expected:

Median for “A” is 2.5.

Actual:

Median for “A” is 3.

**Comment by srikris** [comment]
@znation This seems by design, can't tell if this is better or worse

```
import turicreate as tc
sf=tc.SFrame({'A':[1,2,3,4],'B':['a','a','b','b']})
sf.show()
```
shows median of 3 because its float

```
import turicreate as tc
sf=tc.SFrame({'A':[1.0,2.0,3.0,4.0],'B':['a','a','b','b']})
sf.show()
```
shows median of 2.5 because its float

I don't find that unreasonable.

**Comment by znation** [comment]
Agreed - according to [this StackOverflow post](https://math.stackexchange.com/a/47806), there isn't really consensus on what integer median should mean when there are an even number of integers in a set (and in the case where there is an odd number of integers, clearly one of the integers is exactly the median). Closing this issue as By Design.
