### ISSUE TITLE
GPU Performance on Image Classification/Object Detection

### ISSUE THREAD

**Issue by abhishekpratapa** [apple/turicreate#741]
- IO bottleneck when using GPU on Ubuntu/CUDA
- Multiple GPU not scaling as it should. (i.e. Doubling the number of GPU doesn't speed up the performance by a factor of even close to 2)

**Comment by vade** [comment]
Are you actually getting multi-GPU usage? if you run nvidia-smi do you see secondary or tertiary GPUs having load? I filed #734 - curious how your config differs from ours.

**Comment by srikris** [comment]
@vade By default, Turi Create uses all GPUs. We do observe a speedup of using multiple GPUs but getting 100% usage for this task on the GPUs is tricky because that would depend on the CPU and disk utilization.

This issue is tracking the maximization of GPU resources. 

We are still investigating #734 and its not clear what's going on there.

**Comment by TobyRoseman** [comment]
We have internal tests that do this now.
