### ISSUE TITLE
SFrame and SArray Should have Shuffle Method. 

### ISSUE THREAD

**Issue by TobyRoseman** [apple/turicreate#942]
There appears to be no easy way to randomize the ordering of an SFrame or SArray. We should add a `shuffle` method.

**Comment by nickjong** [comment]
Agreed! We do this in some toolkits by sorting according to a randomized key, but this operation can be extremely expensive. (For example, it's a bottleneck in the object detector.)

Naively, an array can be shuffled much faster than via sorting (should be linear), but I'm not yet sure how that interacts with SFrame lazy evaluation.

**Comment by allenwq** [comment]
+1

**Comment by mxlei01** [comment]
Possible workaround if anyone stumbles on the same problem while I was working on a lot of images on disk.

I create random integers, sorts it, then add row numbers that you can index later. The try except clause is used to remove the column name "id" if we ran this function multiple times, since the add_row_number function does not work if you already have the same id.

```
sf_images["order_id"] = tc.SArray.random_integers(sf_images.num_rows())
sf_images = sf_images.sort(key_column_names="order_id")
try:
    sf_images = sf_images.remove_column("id")
except KeyError:
    pass
sf_images = sf_images.add_row_number(column_name="id")
```

**Comment by TobyRoseman** [comment]
Internally the Object Detector has implemented a O(n log n) [solution](https://github.com/apple/turicreate/blob/c584c1b415aa7ed4e056cbaa457bb620f1445646/src/toolkits/object_detection/od_data_iterator.cpp#L391) in the C++ layer.

**Comment by TobyRoseman** [comment]
SFrame now has shuffle method. Let keep this issue open until SArray also has shuffle method.

**Comment by TobyRoseman** [comment]
SArray got a shuffle method in #3178
