### ISSUE TITLE
Render images directly in Jupyter notebooks

### ISSUE THREAD

**Issue by igiloh** [apple/turicreate#947]
When showing an SFrame in Jupyter notebook (without calling `explore()`, natively in the notebook), it would be great if the output would render images instead of showing their path.

**Comment by znation** [comment]
@shreyajain17 I assigned this to you. You should look at https://github.com/apple/turicreate/blob/master/src/unity/python/turicreate/visualization/_plot.py#L255 for an example of how to render things in IPython (Jupyter) Notebook. You can probably write a much simpler version of this function on the tc.Image type in Python though. The documentation says that instead of _repr_javascript, you can instead directly use something like _repr_jpeg: https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display
