### ISSUE TITLE
Activity classifier should support test dataset with fewer unique labels than the training set

### ISSUE THREAD

**Issue by igiloh** [apple/turicreate#969]
As described in #964 - the user has introduced larger number of labels in the test set than the number of labels the model have been trained on.  
Instead of giving him an explicit error right during the `predict()` portion of `evaluate()` - he got a less intuitive error:
```
ToolkitError: Size of prediction probability vector(3) != number of classes(1)
```

We should probably detect these cases explicitly, right in the beginning of `predict()`, and give an informative error.

**Comment by nickjong** [comment]
Actually, it looks like the opposite: the model was trained with three possible labels (hence the model outputting a prediction vector of size 3), but the dataset being evaluated only has 1 class. This should not generate an error at all and should just work.

**Comment by nickjong** [comment]
Ultimately this is due to these Python-based toolkits not inheriting all of the better-tested code paths from the C++ supervised-learning base classes.... It's possible that just printing a better error message is the correct fix in the short term, with the long-term fix to replace all of the Python code and move to C++.

**Comment by nickjong** [comment]
FYI the relevant code is here: https://github.com/apple/turicreate/blob/f51c2e57ec5b31e8fa8a786127e074dd9f2a50a5/src/unity/toolkits/activity_classification/sequence_iterator.cpp#L33

**Comment by nickjong** [comment]
It turns out that this problem is not specific to the activity classifier: it's arguably an API bug in the evaluation toolkit. I filed #1007. For the purposes of the evaluate() method here, we can work around this issue by providing the class index map explicitly, instead of allowing the evaluation toolkit to infer it from the test-set labels.
